"""Check every manifest against the PLAN.md section 5 contract.

Catches the failure modes that would surface as a blank bubble in the demo:
  - a capability pointing at an endpoint that doesn't exist
  - a {{placeholder}} that nothing can resolve
  - an endpoint URL needing an input the capability never collects
  - a rule referencing a field the seed data doesn't carry

    python3.13 validate.py        # exit 0 = clean
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
PLACEHOLDER = re.compile(r"\{\{([^}]+)\}\}")

# Fields the runtime supplies itself, independent of manifest/seed.
RUNTIME_KEYS = {"mock_base"}

# result.* keys each action returns. get_order is served from the seed file;
# the write actions are generated by the mock API.
ACTION_RESULT_KEYS = {
    "get_order":             {"item", "status", "amount", "currency", "eta",
                              "days_since_delivery", "quantity", "payment",
                              "prescription_on_file"},
    "cancel_order":          {"status", "days_since_delivery", "cancellation_ref",
                              "refund_eta_days"},
    "create_refund":         {"status", "days_since_delivery", "refund_ref",
                              "amount", "refund_eta_days"},
    "create_exchange":       {"status", "days_since_delivery", "exchange_ref",
                              "pickup_date"},
    "create_warranty_claim": {"status", "days_since_delivery", "claim_ref",
                              "callback_hours"},
    "create_reorder":        {"status", "item", "amount", "new_order_id", "eta",
                              "prescription_on_file"},
}

errors: list[str] = []
warnings: list[str] = []


def placeholders(text: str) -> set[str]:
    return {m.strip() for m in PLACEHOLDER.findall(text or "")}


def check_template(where: str, text: str, allowed_plain: set[str], action: str) -> None:
    """Every {{key}} must resolve to an input, a result field, or a runtime key."""
    result_keys = ACTION_RESULT_KEYS.get(action, set())
    for key in placeholders(text):
        if key.startswith("result."):
            field = key.split(".", 1)[1]
            if field not in result_keys:
                errors.append(
                    f"{where}: {{{{{key}}}}} — action '{action}' does not return '{field}' "
                    f"(returns: {', '.join(sorted(result_keys)) or 'nothing'})")
        elif key.startswith("context."):
            continue  # resolved from conversation memory at runtime
        elif key in RUNTIME_KEYS or key in allowed_plain:
            continue
        else:
            errors.append(
                f"{where}: {{{{{key}}}}} is not a collected input "
                f"(inputs: {', '.join(sorted(allowed_plain)) or 'none'})")


def check_manifest(path: pathlib.Path) -> None:
    m = json.loads(path.read_text())
    bid = m["business"]["id"]
    tag = path.name

    if bid != path.stem:
        errors.append(f"{tag}: business.id '{bid}' does not match filename")

    endpoint_ids = {e["id"] for e in m["endpoints"]}
    seed_path = HERE / "seed" / f"{bid}.json"
    if not seed_path.exists():
        errors.append(f"{tag}: no seed file at seed/{bid}.json")
        return
    seed = json.loads(seed_path.read_text())
    seed_order_keys = set(seed["orders"][0]) if seed["orders"] else set()

    for cap in m["capabilities"]:
        cid = cap["id"]
        action = cap["action"]
        where = f"{tag}:{cid}"

        if action not in endpoint_ids:
            errors.append(f"{where}: action '{action}' has no matching endpoint "
                          f"(have: {', '.join(sorted(endpoint_ids))})")
            continue

        inputs = {i["name"] for i in cap["required_inputs"]}

        # The endpoint URL may only interpolate collected inputs / runtime keys.
        url = next(e["url"] for e in m["endpoints"] if e["id"] == action)
        for key in placeholders(url):
            if key not in inputs and key not in RUNTIME_KEYS:
                errors.append(f"{where}: endpoint URL needs {{{{{key}}}}} but the "
                              f"capability never collects it")

        check_template(f"{where}.response", cap["response"], inputs, action)
        check_template(f"{where}.receipt", cap["receipt"]["label"], inputs, action)

        for rule in cap.get("rules", []):
            check_template(f"{where}.rule[{rule['id']}].deny", rule["deny"], inputs, action)
            # rules read result.* directly in `when`
            for field in re.findall(r"result\.(\w+)", rule["when"]):
                if field not in ACTION_RESULT_KEYS.get(action, set()):
                    errors.append(f"{where}: rule '{rule['id']}' tests result.{field}, "
                                  f"which action '{action}' does not return")
                if field not in seed_order_keys and action == "get_order":
                    warnings.append(f"{where}: rule '{rule['id']}' tests result.{field}, "
                                    f"absent from seed orders")

        if cap.get("confirm") and not cap["receipt"]:
            warnings.append(f"{where}: confirm=true but no receipt")

    # Unused endpoints are dead weight in a manifest that claims to be the contract.
    used = {c["action"] for c in m["capabilities"]}
    for extra in endpoint_ids - used:
        warnings.append(f"{tag}: endpoint '{extra}' is not referenced by any capability")


def main() -> int:
    manifests = sorted((HERE / "manifests").glob("*.json"))
    if not manifests:
        print("no manifests found — run build_manifests.py first")
        return 1

    for path in manifests:
        check_manifest(path)

    for w in warnings:
        print(f"  warn  {w}")
    for e in errors:
        print(f"  FAIL  {e}")

    print()
    if errors:
        print(f"{len(manifests)} manifests · {len(errors)} error(s) · {len(warnings)} warning(s)")
        return 1
    print(f"{len(manifests)} manifests valid · {len(warnings)} warning(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
